import type {Metadata} from "next";
import "@/style/globals.css";
import React from "react";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {Inter} from 'next/font/google'
import {NextSessionProvider} from "@/components/providers/session-provider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className}`}>
        <NextSessionProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
        </NextSessionProvider>
        </body>
        </html>
    );
}
